[package]
name = "t9cc"
version = "0.1.0"
edition = "2021"

[dependencies]
toml = "0.8"
serde = { version = "1.0", features = ["derive"] }
rayon = "1.8"

[[bin]]
name = "test_runner"
path = "test/test_runner.rs"
