name: Check

on:
  push:

defaults:
  run:
    shell: bash

concurrency:
  group: check
  cancel-in-progress: true
  

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo test --all-features
      
